##################################################################################################
# authjs-idp
##################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: authjs-idp
  labels:
    app: authjs-idp
    service: authjs
spec:
  ports:
    - port: 8080
      name: external
      appProtocol: http
      protocol: TCP
  selector:
    app: authjs-idp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authjs-idp
  labels:
    account: authjs-idp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authjs-idp
  labels:
    app: authjs-idp
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authjs-idp
      version: v1
  template:
    metadata:
      labels:
        app: authjs-idp
        version: v1
    spec:
      serviceAccountName: authjs-idp
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: authjs-idp
          image: bitnami/keycloak:23
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 400m
              memory: 400Mi
            requests:
              cpu: 200m
              memory: 200Mi
          tty: true
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: authjs-idp
            - secretRef:
                name: authjs-idp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authjs-idp
data:
  KEYCLOAK_CREATE_ADMIN_USER: "true"
  KEYCLOAK_DATABASE_VENDOR: "postgresql"
  KEYCLOAK_DATABASE_HOST: "authjs-db"
  KEYCLOAK_DATABASE_PORT: "5432"
  KC_HOSTNAME_URL: "https://authjs-idp.aimerzarashi.com"
  KC_HOSTNAME_ADMIN_URL: "https://authjs-idp.aimerzarashi.com"
  KEYCLOAK_DATABASE_NAME: bitnami_keycloak
  KEYCLOAK_DATABASE_SCHEMA: public
---
apiVersion: v1
kind: Secret
metadata:
  name: authjs-idp
type: Opaque
data:
  KEYCLOAK_ADMIN_USER: dXNlcg== #user
  KEYCLOAK_ADMIN_PASSWORD: Yml0bmFtaQ== #bitnami
  KEYCLOAK_DATABASE_USER: Ym5fa2V5Y2xvYWs= #bn_keycloak
  KEYCLOAK_DATABASE_PASSWORD: cGFzc3dvcmQ= #password