##################################################################################################
# authjs-web
##################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: authjs-web
  labels:
    app: authjs-web
    service: authjs
spec:
  ports:
    - port: 3000
      name: tcp
      appProtocol: http
  selector:
    app: authjs-web
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authjs-web
  labels:
    account: authjs-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authjs-web
  labels:
    app: authjs-web
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authjs-web
      version: v1
  template:
    metadata:
      labels:
        app: authjs-web
        version: v1
    spec:
      serviceAccountName: authjs-web
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: authjs-web
          image: aimerzarashi/authjs-v5-keycloak:0.0.1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 500m
              memory: 500Mi
          tty: true
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: authjs-web
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authjs-web
data:
  AUTH_URL: "https://authjs-web.aimerzarashi.com"
  AUTH_TRUST_HOST: "true"
  AUTH_SECRET: ObjQQ/kxEEp8p2jwTZdfmHOxJFDJ5UxnBA7+d0FZl0E=
  AUTH_KEYCLOAK_ID: web
  AUTH_KEYCLOAK_SECRET: vUMgfu8OciGT8QXnaSoeJQAYlGpgheFb
  AUTH_KEYCLOAK_ISSUER: https://authjs-idp.aimerzarashi.com/realms/demo